site_name: Synalinks
site_description: Keras based LM framework for neuro-symbolic applications
site_url: https://synalinks.github.io/synalinks
repo_url: https://github.com/SynaLinks/synalinks
repo_name: SynaLinks/synalinks
theme:
  name: material
  logo: assets/synalinks_logo.png
  favicon: assets/synalinks_favicon.png
  features:
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
  theme:
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - mkdocstrings:
      default_handler: python
  - glightbox
  - llmstxt:
      full_output: llms-full.txt
      markdown_description: Keras based LM framework for neuro-symbolic applications and In-Context learning
      sections:
        Usage documentation:
        - Introduction.md
        - Synalinks API/Programs API/Program training API.md
        - Synalinks API/Programs API/The Program class.md
        - Synalinks API/Programs API/The Sequential class.md
        - Synalinks API/* module.md
        - Synalinks API/Rewards/* reward.md
        - Synalinks API/Rewards/* wrappers.md

nav:
  - index.md
  - Introduction.md
  - Guides:
    - guides/Getting Started.md
    - guides/Data Models.md
    - guides/Programs.md
    - guides/Modules.md
    - guides/Agents.md
    - guides/Knowledge Base.md
    - guides/Training.md
    - guides/Observability.md
    - guides/Input Guard.md
    - guides/Output Guard.md
  - Code Examples:
    - Code Examples/First Steps.md
    - Code Examples/Functional API.md
    - Code Examples/Subclassing.md
    - Code Examples/Sequential API.md
    - Code Examples/Mixing Strategy.md
    - Code Examples/Parallel Branches.md
    - Code Examples/Decisions.md
    - Code Examples/Conditional Branches.md
    - Code Examples/Data Model Operators.md
    - Code Examples/JSON Ops.md
    - Code Examples/Conversational Applications.md
    - Code Examples/Reward Metrics And Optimizers.md
    - Code Examples/Training Programs.md
    - Code Examples/Implementing Custom Modules Via Subclassing.md
    - Code Examples/Autonomous Agent.md
    - Code Examples/Interactive Agent.md
    - Code Examples/Knowledge Extraction and Storage.md
    - Code Examples/Document RAG.md
    - Code Examples/RAG Agent.md
    - Code Examples/MCP Agent.md
  - Modules: Synalinks API/Modules API/index.md
  - FAQ.md
  - CheatSheet.md
  - Differences with Keras.md
  - Differences with DSPy.md
  - Synalinks API:
    - Synalinks API/Language Models API.md
    - Synalinks API/Embedding Models API.md
    - Synalinks API/Knowledge Bases API.md
    - Data Models API:
      - Synalinks API/Data Models API/index.md
      - Synalinks API/Data Models API/The DataModel class.md
      - Synalinks API/Data Models API/The JsonDataModel class.md
      - Synalinks API/Data Models API/The SymbolicDataModel class.md
      - Synalinks API/Data Models API/The Variable class.md
      - Synalinks API/Data Models API/The Base DataModels.md
    - Programs API:
      - Synalinks API/Programs API/index.md
      - Synalinks API/Programs API/The Program class.md
      - Synalinks API/Programs API/The Sequential class.md
      - Synalinks API/Programs API/Program training API.md
      - Program Saving API:
        - Synalinks API/Programs API/Program Saving API/Program saving and loading.md
        - Synalinks API/Programs API/Program Saving API/Variable saving and loading.md
    - Modules API:
      - Synalinks API/Modules API/index.md
      - Synalinks API/Modules API/Base Module class.md
      - Core Modules:
        - Synalinks API/Modules API/Core Modules/index.md
        - Synalinks API/Modules API/Core Modules/Input module.md
        - Synalinks API/Modules API/Core Modules/Identity module.md
        - Synalinks API/Modules API/Core Modules/Not module.md
        - Synalinks API/Modules API/Core Modules/Generator module.md
        - Synalinks API/Modules API/Core Modules/Decision module.md
        - Synalinks API/Modules API/Core Modules/Action module.md
        - Synalinks API/Modules API/Core Modules/Branch module.md
        - Synalinks API/Modules API/Core Modules/Tool module.md
      - Agents Modules:
        - Synalinks API/Modules API/Agents Modules/index.md
        - Synalinks API/Modules API/Agents Modules/FunctionCallingAgent module.md
      - Knowledge Modules:
        - Synalinks API/Modules API/Knowledge Modules/index.md
        - Synalinks API/Modules API/Knowledge Modules/EmbedKnowledge module.md
        - Synalinks API/Modules API/Knowledge Modules/UpdateKnowledge module.md
        - Synalinks API/Modules API/Knowledge Modules/RetrieveKnowledge module.md
      - Masking Modules:
        - Synalinks API/Modules API/Masking Modules/index.md
        - Synalinks API/Modules API/Masking Modules/InMask module.md
        - Synalinks API/Modules API/Masking Modules/OutMask module.md
      - Merging Modules:
        - Synalinks API/Modules API/Merging Modules/index.md
        - Synalinks API/Modules API/Merging Modules/Concat module.md
        - Synalinks API/Modules API/Merging Modules/And module.md
        - Synalinks API/Modules API/Merging Modules/Or module.md
        - Synalinks API/Modules API/Merging Modules/Xor module.md
      - Test Time Compute Modules:
        - Synalinks API/Modules API/Test Time Compute Modules/index.md
        - Synalinks API/Modules API/Test Time Compute Modules/ChainOfThought module.md
        - Synalinks API/Modules API/Test Time Compute Modules/SelfCritique module.md
      - Synthesis Modules:
        - Synalinks API/Modules API/Synthesis Modules/index.md
        - Synalinks API/Modules API/Synthesis Modules/PythonSynthesis module.md
        - Synalinks API/Modules API/Synthesis Modules/SequentialPlanSynthesis module.md
    - Callbacks API:
      - Synalinks API/Callbacks API/index.md
      - Synalinks API/Callbacks API/Base Callback class.md
      - Synalinks API/Callbacks API/ProgramCheckpoint.md
      - Synalinks API/Callbacks API/CSVLogger.md
      - Synalinks API/Callbacks API/BackUpAndRestore.md
      - Synalinks API/Callbacks API/EarlyStopping.md
      - Synalinks API/Callbacks API/Monitor.md
    - Hooks API:
      - Synalinks API/Hooks API/index.md
      - Synalinks API/Hooks API/Base Hook class.md
      - Synalinks API/Hooks API/Logger.md
      - Synalinks API/Hooks API/Monitor.md
    - Ops API:
      - Synalinks API/Ops API/index.md
      - Synalinks API/Ops API/JSON Ops.md
      - Synalinks API/Ops API/Language Models Ops.md
      - Synalinks API/Ops API/Embedding Models Ops.md
    - Optimizers API:
      - Synalinks API/Optimizers API/index.md
      - Synalinks API/Optimizers API/Base Optimizer class.md
      - Synalinks API/Optimizers API/RandomFewShot.md
      - Synalinks API/Optimizers API/OMEGA.md
    - Metrics:
      - Synalinks API/Metrics/index.md
      - Synalinks API/Metrics/Base Metric class.md
      - Synalinks API/Metrics/Metric wrappers and reduction metrics.md
      - Synalinks API/Metrics/Regression metrics.md
      - Synalinks API/Metrics/FScore metrics.md
    - Rewards:
      - Synalinks API/Rewards/index.md
      - Synalinks API/Rewards/ExactMatch reward.md
      - Synalinks API/Rewards/CosineSimilarity reward.md
      - Synalinks API/Rewards/LMAsJudge reward.md
      - Synalinks API/Rewards/Reward wrappers.md
    - Built-in Datasets:
      - Synalinks API/Built-in Datasets/index.md
      - Synalinks API/Built-in Datasets/GSM8K.md
      - Synalinks API/Built-in Datasets/HotpotQA.md
      - Synalinks API/Built-in Datasets/ARC-AGI.md
    - Utilities:
      - Synalinks API/Utilities/Program plotting utilities.md
      - Synalinks API/Utilities/More plotting utilities.md
      - Synalinks API/Utilities/NLP utilities.md
    - Synalinks API/Config.md
  - Deployment:
    - Deployment/Building a REST API.md
  - Observability:
    - Observability/MLflow.md